theme: jekyll-theme-minimal

title: Josh Shadik
email: joshshadik@gmail.com
github_username: joshshadik
home_url: https://joshshadik.github.io
github_url: https://github.com/joshshadik
resume_url: https://docs.google.com/document/d/1fFVzwFGK0gmkqwFW5ucwceRZSe5AAyOy1qQoWStqRYU/

jellyface_url: https://joshshadik.github.io/jelly-face/
voxsculpt_url: https://experiments.withgoogle.com/chrome/voxsculpt
cubenado_url: https://joshshadik.github.io/cubenado/
cubepull_url: https://joshshadik.github.io/pull-cube

fragem_url: https://steamcommunity.com/sharedfiles/filedetails/?id=699533551
mechatrigger_url: http://gamedev.msu.edu/mecha-trigger/
dawnofdayx_url: http://gamedev.msu.edu/dawn-of-day-x/
ggj_url: http://globalgamejam.org/users/josh-shadik
googleplay_url: https://play.google.com/store/apps/developer?id=AppleBatApps

cylon_url: https://sketchfab.com/models/26702723fe8c404aab86f1bbf7893324

vid_demo_reel_url: https://vimeo.com/161271383
vid_dim_portals_url: https://www.youtube.com/watch?v=0ihZ6DItYvk
vid_fragem_url: https://www.youtube.com/watch?v=_g2r0uEzQrI
vid_mechatrigger_url: http://www.youtube.com/watch?v=GV7wYv0F_NE